- type: replace
  path: /instance_groups/name=log-api/jobs/-
  value:
    name: reverse_log_proxy_gateway
    release: loggregator
    properties:
      logs_provider:
        ca_cert: "((loggregator_rlp_gateway.ca))"
        client_cert: "((loggregator_rlp_gateway.certificate))"
        client_key: "((loggregator_rlp_gateway.private_key))"
      cc:
        capi_internal_addr: https://cloud-controller-ng.service.cf.internal:9023
        ca_cert: ((loggregator_rlp_gatway_tls_cc.ca))
        cert: ((loggregator_rlp_gatway_tls_cc.certificate))
        key: ((loggregator_rlp_gatway_tls_cc.private_key))
        common_name: cloud-controller-ng.service.cf.internal
      uaa:
        ca_cert: ((uaa_ca.certificate))
        client_id: doppler
        client_secret: ((uaa_clients_doppler_secret))
        internal_addr: https://uaa.service.cf.internal:8443

- type: replace
  path: /instance_groups/name=log-api/jobs/name=route_registrar/properties?/route_registrar/routes/-
  value:
    name: log-api-reverse-proxy
    port: 8088
    registration_interval: 20s
    uris:
    - log-stream.((system_domain))
    - '*.log-stream.((system_domain))'

- type: replace
  path: /variables/-
  value:
    name: loggregator_rlp_gateway
    type: certificate
    options:
      ca: loggregator_ca
      common_name: rlp_gateway
      extended_key_usage:
      - client_auth
- type: replace
  path: /variables/-
  value:
    name: loggregator_rlp_gatway_tls_cc
    type: certificate
    options:
      ca: service_cf_internal_ca
      common_name: log-api
      extended_key_usage:
      - client_auth
